import { Inter } from "next/font/google";
import "./globals.css";
import { ComponentsProvider } from "@/contexts/ComponentsContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className="dark bg-white lg:bg-zinc-100 dark:bg-zinc-900 dark:lg:bg-zinc-950 dark:text-white"
    >
      <body className={inter.className}>
        <ComponentsProvider>{children}</ComponentsProvider>
      </body>
    </html>
  );
}
